#!/usr/bin/env bash
# script that prints record infos

print_domain_info() {
    domain="$1"
    subdomain="$2"
    dig_output=$(dig "$subdomain.$domain")
    record_type=$(echo "$dig_output" | awk '/ANSWER SECTION/{getline; print $4}')
    ip_address=$(echo "$dig_output" | awk '/ANSWER SECTION/{getline; print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $ip_address"
}

if [ "$#" -eq 2 ]; then
    print_domain_info "$1" "$2"
else
    default_subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${default_subdomains[@]}"; do
        print_domain_info "$1" "$subdomain"
    done
fi
